CREATE TABLE ACADEMIC_FORMATION 
    ( 
     ID_ACADEMIC_FORMATION INTEGER  NOT NULL , 
     FORMATION_NAME        VARCHAR2 (50 CHAR) , 
     ID_DEGREE_LEVEL       INTEGER  NOT NULL , 
     ID_INSTITUTION        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ACADEMIC_FORMATION 
    ADD CONSTRAINT ACADEMIC_FORMATION_PK PRIMARY KEY ( ID_ACADEMIC_FORMATION );
