CREATE TABLE ASSESSMENT_TYPE 
    ( 
     ID_ASSESSMENT_TYPE INTEGER  NOT NULL , 
     DESCRIPTION        VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE ASSESSMENT_TYPE 
    ADD CONSTRAINT ASSESSMENT_TYPE_PK PRIMARY KEY ( ID_ASSESSMENT_TYPE );
