CREATE TABLE ATTENDANCE 
    ( 
     ID_ATTENDANCE INTEGER  NOT NULL , 
     "DATE"        DATE , 
     DETAILS       VARCHAR2 (10 BYTE) , 
     ID_SCHEDULE   INTEGER  NOT NULL , 
     ID_STUDENT    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ATTENDANCE 
    ADD CONSTRAINT ATTENDANCE_PK PRIMARY KEY ( ID_ATTENDANCE ) ;
