CREATE TABLE CAMPUS 
    ( 
     ID_CAMPUS   INTEGER  NOT NULL , 
     NAME_CAMPUS VARCHAR2 (40 CHAR)  NOT NULL , 
     ID_LOCATION INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CAMPUS 
    ADD CONSTRAINT CAMPUS_PK PRIMARY KEY ( ID_CAMPUS ) ;
