CREATE TABLE CLASSROOM 
    ( 
     ID_CLASSROOM       INTEGER  NOT NULL , 
     NAME_CLASSROOM     VARCHAR2 (30 CHAR) , 
     CAPACITY_CLASSROOM INTEGER , 
     ID_CAMPUS          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CLASSROOM 
    ADD CONSTRAINT CLASSROOM_PK PRIMARY KEY ( ID_CLASSROOM ) ;
