CREATE TABLE COURSE_PLAN 
    ( 
     ID_COURSE_PLAN INTEGER  NOT NULL , 
     YEAR           INTEGER , 
     DESCRIPTION    VARCHAR2 (30 BYTE) 
    ) 
;

ALTER TABLE COURSE_PLAN 
    ADD CONSTRAINT COURSE_PLAN_PK PRIMARY KEY ( ID_COURSE_PLAN ) ;
