CREATE TABLE COURSE 
    ( 
     ID_COURSE          INTEGER  NOT NULL , 
     MAX_CAPACITY       INTEGER , 
     ID_SUBJETC         INTEGER  NOT NULL , 
     ID_PERIOD          INTEGER  NOT NULL , 
     ID_SUBJECT_TEACHER INTEGER  NOT NULL , 
     ID_SCHEDULE        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE COURSE 
    ADD CONSTRAINT SUBJECT_OFFERING_PK PRIMARY KEY ( ID_COURSE ) ;
