CREATE TABLE DEGREE_LEVEL 
    ( 
     ID_DEGREE_LEVEL   INTEGER  NOT NULL , 
     NAME_DEGREE_LEVEL VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE DEGREE_LEVEL 
    ADD CONSTRAINT DEGREE_LEVEL_PK PRIMARY KEY ( ID_DEGREE_LEVEL ) ;
