CREATE TABLE ENROLLMENT_STATUS 
    ( 
     ID_ENROLLMENT_STATUS INTEGER  NOT NULL , 
     STATUS               VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE ENROLLMENT_STATUS 
    ADD CONSTRAINT ENROLLMENT_STATUS_PK PRIMARY KEY ( ID_ENROLLMENT_STATUS ) ;
