CREATE TABLE ENROLLMENT 
    ( 
     ID_ENROLLEMNT        INTEGER  NOT NULL , 
     ID_STUDENT           INTEGER  NOT NULL , 
     ID_SUBJETC           INTEGER  NOT NULL , 
     ID_PERIOD            INTEGER  NOT NULL , 
     DESCRIPTION          VARCHAR2 (40 CHAR) , 
     ID_ENROLLMENT_STATUS INTEGER  NOT NULL , 
     ID_COURSE            INTEGER  NOT NULL , 
     "DATE"               DATE 
    ) 
;

ALTER TABLE ENROLLMENT 
    ADD CONSTRAINT ENROLLMENT_PK PRIMARY KEY ( ID_ENROLLEMNT, ID_ENROLLMENT_STATUS ) ;
