CREATE TABLE FINAL_GRADE 
    ( 
     ID_FINAL_GRADE        INTEGER  NOT NULL , 
     GRADE                 INTEGER , 
     ID_STUDENT            INTEGER  NOT NULL , 
     ID_STUDENT_EVALUATION INTEGER  NOT NULL , 
     ID_COURSE             INTEGER  NOT NULL 
    ) 
;

ALTER TABLE FINAL_GRADE 
    ADD CONSTRAINT FINAL_GRADE_PK PRIMARY KEY ( ID_FINAL_GRADE ) ;
