CREATE TABLE GRADE_HISTORY 
    ( 
     ID_GRADE_HISTORY INTEGER  NOT NULL , 
     DESCRIPTION      VARCHAR2 (50 CHAR) , 
     ID_FINAL_GRADE   INTEGER  NOT NULL 
    ) 
;

ALTER TABLE GRADE_HISTORY 
    ADD CONSTRAINT GRADE_HISTORY_PK PRIMARY KEY ( ID_GRADE_HISTORY ) ;
