CREATE TABLE GRADE_SCALE 
    ( 
     ID_GRADE_SCALE INTEGER  NOT NULL , 
     NAME           VARCHAR2 (30 CHAR) , 
     MIN_VALUE      INTEGER , 
     MAX_VALUE      INTEGER , 
     DESCRIPTION    VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE GRADE_SCALE 
    ADD CONSTRAINT GRADE_SCALE_PK PRIMARY KEY ( ID_GRADE_SCALE ) ;
