CREATE TABLE GRADE 
    ( 
     ID_GRADE       INTEGER  NOT NULL , 
     GRADE          INTEGER , 
     ID_GRADE_SCALE INTEGER  NOT NULL 
    ) 
;

ALTER TABLE GRADE 
    ADD CONSTRAINT GRADE_PK PRIMARY KEY ( ID_GRADE ) ;
