CREATE TABLE INSTITUTION 
    ( 
     ID_INSTITUTION   INTEGER  NOT NULL , 
     NAME_INSTITUTION VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE INSTITUTION 
    ADD CONSTRAINT INSTITUTION_PK PRIMARY KEY ( ID_INSTITUTION ) ;
