CREATE TABLE PERIOD 
    ( 
     ID_PERIOD               INTEGER  NOT NULL , 
     DESCRIPTION             VARCHAR2 (30 BYTE) , 
     YEAR                    INTEGER , 
     SUBJECT_CANCELATION     DATE , 
     SEMESTER_CANCELATION    DATE , 
     SEMESTER                INTEGER , 
     SUMPLEMENTARY_EXAM_DATE DATE 
    ) 
;

ALTER TABLE PERIOD 
    ADD CONSTRAINT PERIOD_PK PRIMARY KEY ( ID_PERIOD ) ;
