CREATE TABLE PREREQUISITE 
    ( 
     ID_PREREQUISITE INTEGER  NOT NULL , 
     DESCRIPTION     VARCHAR2 (30 BYTE) , 
     ID_SUBJETC      INTEGER  NOT NULL , 
     ID_SUBJETC2     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PREREQUISITE 
    ADD CONSTRAINT PREREQUISITE_PK PRIMARY KEY ( ID_PREREQUISITE, ID_SUBJETC2 ) ;
