CREATE TABLE PROGRAM 
    ( 
     ID_PROGRAM     INTEGER  NOT NULL , 
     CODE_PROGRAM   INTEGER , 
     NAME_PROGRAM   VARCHAR2 (30 BYTE) , 
     TOTAL_CREDITS  INTEGER , 
     ID_FACULTY     INTEGER  NOT NULL , 
     ID_COURSE_PLAN INTEGER  NOT NULL 
    ) 
;

ALTER TABLE PROGRAM 
    ADD CONSTRAINT PROGRAM_PK PRIMARY KEY ( ID_PROGRAM ) ;

ALTER TABLE PROGRAM 
    ADD CONSTRAINT PROGRAM_CODE_PROGRAM_UN UNIQUE ( CODE_PROGRAM ) ;
