CREATE TABLE "RESOURCE" 
    ( 
     ID_RESOURCE INTEGER  NOT NULL , 
     TITLE       VARCHAR2 (40 CHAR) , 
     TYPE        VARCHAR2 (30 CHAR) , 
     URL         VARCHAR2 (50 BYTE) 
    ) 
;

ALTER TABLE "RESOURCE" 
    ADD CONSTRAINT RESOURCE_PK PRIMARY KEY ( ID_RESOURCE ) ;
