CREATE TABLE SCHEDULE 
    ( 
     ID_SCHEDULE  INTEGER  NOT NULL , 
     START_TIME   TIMESTAMP , 
     END_TIME     TIMESTAMP , 
     ID_CLASSROOM INTEGER  NOT NULL , 
     ID_DAY       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE SCHEDULE 
    ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY ( ID_SCHEDULE ) ;
