CREATE TABLE STUDENT 
    ( 
     ID_STUDENT         INTEGER  NOT NULL , 
     NAME_STUDENT       VARCHAR2 (30 BYTE) , 
     SURNAME_STUDENT    VARCHAR2 (30 BYTE) , 
     STUDENT_NI         VARCHAR2 (30 BYTE) , 
     EMAIL_STUDENT      VARCHAR2 (50 BYTE) , 
     PHONE_NUMBER       VARCHAR2 (10 CHAR) , 
     SEMESTER_NUMBER    INTEGER , 
     ID_STUDENT_RISK    INTEGER  NOT NULL , 
     ID_PROGRAM         INTEGER  NOT NULL , 
     ID_USER_ACCOUNT    INTEGER  NOT NULL , 
     ID_STUDENT_STATUS  INTEGER  NOT NULL , 
     ID_STUDENT_CREDITS INTEGER  NOT NULL 
    ) 
;

ALTER TABLE STUDENT 
    ADD CONSTRAINT STUDENT_PK PRIMARY KEY ( ID_STUDENT ) ;

ALTER TABLE STUDENT 
    ADD CONSTRAINT STUDENT_STUDENT_NI_UN UNIQUE ( STUDENT_NI ) ;
