CREATE TABLE STUDENT_CREDITS 
    ( 
     ID_STUDENT_CREDITS INTEGER  NOT NULL , 
     MIN_CREDITS        INTEGER , 
     MAX_CREDITS        INTEGER 
    ) 
;

ALTER TABLE STUDENT_CREDITS 
    ADD CONSTRAINT STUDENT_CREDITS_PK PRIMARY KEY ( ID_STUDENT_CREDITS ) ;
