CREATE TABLE STUDENT_STATUS 
    ( 
     ID_STUDENT_STATUS INTEGER  NOT NULL , 
     STATUS            VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE STUDENT_STATUS 
    ADD CONSTRAINT STUDENT_STATUS_PK PRIMARY KEY ( ID_STUDENT_STATUS ) ;
