CREATE TABLE STUDENT_RISK 
    ( 
     ID_STUDENT_RISK INTEGER  NOT NULL , 
     RISK_LEVEL      INTEGER , 
     MAXIM_CREDITS   INTEGER , 
     MIN_CREDITS     INTEGER 
    ) 
;

ALTER TABLE STUDENT_RISK 
    ADD CONSTRAINT STUDENT_RISK_PK PRIMARY KEY ( ID_STUDENT_RISK ) ;
