CREATE TABLE SUBJECT_TEACHER 
    ( 
     ID_SUBJECT_TEACHER INTEGER  NOT NULL , 
     ID_TEACHER         INTEGER  NOT NULL 
    ) 
;

ALTER TABLE SUBJECT_TEACHER 
    ADD CONSTRAINT SUBJECT_TEACHER_PK PRIMARY KEY ( ID_SUBJECT_TEACHER ) ;
