CREATE TABLE SUBJECT 
    ( 
     ID_SUBJETC      INTEGER  NOT NULL , 
     NAME_SUBJECT    VARCHAR2 (40 BYTE) , 
     CREDITS         INTEGER , 
     START_TIME      DATE , 
     WEEKLY_HOURS    INTEGER , 
     ID_PROGRAM      INTEGER  NOT NULL , 
     ID_RESOURCE     INTEGER  NOT NULL , 
     ID_PREREQUISITE INTEGER  NOT NULL , 
     ID_SUBJECT_TYPE INTEGER  NOT NULL , 
     ID_SCHEDULE     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE SUBJECT 
    ADD CONSTRAINT SUBJECT_PK PRIMARY KEY ( ID_SUBJETC ) ;
