CREATE TABLE SUBJECT_TYPE 
    ( 
     ID_SUBJECT_TYPE INTEGER  NOT NULL , 
     DESCRIPTION     VARCHAR2 (50 CHAR) 
    ) 
;

ALTER TABLE SUBJECT_TYPE 
    ADD CONSTRAINT SUBJECT_TYPE_PK PRIMARY KEY ( ID_SUBJECT_TYPE ) ;
