CREATE TABLE TEACHER_LOAD 
    ( 
     ID_TEACHER_LOAD INTEGER  NOT NULL , 
     MAX_HOURS       INTEGER , 
     MIN_HOURS       INTEGER 
    ) 
;

ALTER TABLE TEACHER_LOAD 
    ADD CONSTRAINT TEACHER_LOAD_PK PRIMARY KEY ( ID_TEACHER_LOAD ) ;
