CREATE TABLE TEACHER 
    ( 
     ID_TEACHER            INTEGER  NOT NULL , 
     NAME_TEACHER          VARCHAR2 (30 CHAR) , 
     SURNAME_TEACHER       VARCHAR2 (30 CHAR) , 
     NUMBER_PHONE          VARCHAR2 (30 CHAR) , 
     ID_USER_ACCOUNT       INTEGER  NOT NULL , 
     ID_ACADEMIC_FORMATION INTEGER  NOT NULL , 
     ID_TEACHER_LOAD       INTEGER  NOT NULL 
    ) 
;

ALTER TABLE TEACHER 
    ADD CONSTRAINT TEACHER_PK PRIMARY KEY ( ID_TEACHER ) ;
