CREATE TABLE USER_ACCOUNT 
    ( 
     ID_USER_ACCOUNT INTEGER  NOT NULL , 
     USERNAME        VARCHAR2 (10 BYTE) , 
     PASSWORD        VARCHAR2 (30 CHAR) 
    ) 
;

ALTER TABLE USER_ACCOUNT 
    ADD CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY ( ID_USER_ACCOUNT ) ;
